In [46]:
#1.Grid Search CV SVC
# i have taken bupa research cv to predict the liver disorder
import numpy as np
import pandas as pd

In [47]:
df=pd.read_csv('bupa.csv',delimiter=',',header=None)
df

0   1   2   3    4     5  6
0    85  92  45  27   31   0.0  1
1    85  64  59  32   23   0.0  2
2    86  54  33  16   54   0.0  2
3    91  78  34  24   36   0.0  2
4    87  70  12  28   10   0.0  2
..   ..  ..  ..  ..  ...   ... ..
340  99  75  26  24   41  12.0  1
341  96  69  53  43  203  12.0  2
342  98  77  55  35   89  15.0  1
343  91  68  27  26   14  16.0  1
344  98  99  57  45   65  20.0  1

[345 rows x 7 columns]

In [48]:
column_labels=[' mean corpuscular volume','alkphos alkaline phosphotase','sgpt alanine aminotransferase',' sgot aspartate aminotransferase','gammagt gamma-glutamyl transpeptidase','drinks number of half-pint equivalents of alcoholic beverages drunk per day','selector field created by the BUPA researchers']
df.columns=column_labels

In [49]:
df.head()

mean corpuscular volume  alkphos alkaline phosphotase  \
0                        85                            92   
1                        85                            64   
2                        86                            54   
3                        91                            78   
4                        87                            70   

   sgpt alanine aminotransferase   sgot aspartate aminotransferase  \
0                             45                                27   
1                             59                                32   
2                             33                                16   
3                             34                                24   
4                             12                                28   

   gammagt gamma-glutamyl transpeptidase  \
0                                     31   
1                                     23   
2                                     54   
3                                     36   
4                                     10   

   drinks number of half-pint equivalents of alcoholic beverages drunk per day  \
0                                                0.0                             
1                                                0.0                             
2                                                0.0                             
3                                                0.0                             
4                                                0.0                             

   selector field created by the BUPA researchers  
0                                               1  
1                                               2  
2                                               2  
3                                               2  
4                                               2

In [50]:
df.corr()

mean corpuscular volume  \
 mean corpuscular volume                                            1.000000   
alkphos alkaline phosphotase                                        0.044103   
sgpt alanine aminotransferase                                       0.147695   
 sgot aspartate aminotransferase                                    0.187765   
gammagt gamma-glutamyl transpeptidase                               0.222314   
drinks number of half-pint equivalents of alcoh...                  0.312680   
selector field created by the BUPA researchers                     -0.091070   

                                                    alkphos alkaline phosphotase  \
 mean corpuscular volume                                                0.044103   
alkphos alkaline phosphotase                                            1.000000   
sgpt alanine aminotransferase                                           0.076208   
 sgot aspartate aminotransferase                                        0.146057   
gammagt gamma-glutamyl transpeptidase                                   0.133140   
drinks number of half-pint equivalents of alcoh...                      0.100796   
selector field created by the BUPA researchers                         -0.098050   

                                                    sgpt alanine aminotransferase  \
 mean corpuscular volume                                                 0.147695   
alkphos alkaline phosphotase                                             0.076208   
sgpt alanine aminotransferase                                            1.000000   
 sgot aspartate aminotransferase                                         0.739675   
gammagt gamma-glutamyl transpeptidase                                    0.503435   
drinks number of half-pint equivalents of alcoh...                       0.206848   
selector field created by the BUPA researchers                          -0.035009   

                                                     sgot aspartate aminotransferase  \
 mean corpuscular volume                                                    0.187765   
alkphos alkaline phosphotase                                                0.146057   
sgpt alanine aminotransferase                                               0.739675   
 sgot aspartate aminotransferase                                            1.000000   
gammagt gamma-glutamyl transpeptidase                                       0.527626   
drinks number of half-pint equivalents of alcoh...                          0.279588   
selector field created by the BUPA researchers                              0.157356   

                                                    gammagt gamma-glutamyl transpeptidase  \
 mean corpuscular volume                                                         0.222314   
alkphos alkaline phosphotase                                                     0.133140   
sgpt alanine aminotransferase                                                    0.503435   
 sgot aspartate aminotransferase                                                 0.527626   
gammagt gamma-glutamyl transpeptidase                                            1.000000   
drinks number of half-pint equivalents of alcoh...                               0.341224   
selector field created by the BUPA researchers                                   0.146393   

                                                    drinks number of half-pint equivalents of alcoholic beverages drunk per day  \
 mean corpuscular volume                                                                     0.312680                             
alkphos alkaline phosphotase                                                                 0.100796                             
sgpt alanine aminotransferase                                                                0.206848                             
 sgot aspartate aminotransferase                                                    

In [51]:
# our main intention is to analyse data with crossvalidation and gridsearchcv wil skip most of EDA process
#i will analyse data as it is

In [52]:
#separating the input variable
import numpy as np
X=df.drop(columns=["selector field created by the BUPA researchers"])
y=df['selector field created by the BUPA researchers']

In [53]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 5,test_size=0.25)

In [54]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [55]:
#Fitting Kernel SVM to the Training set
from sklearn.svm import SVC
classifier =SVC(kernel='linear',random_state=0)

In [56]:
classifier.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=0,
    shrinking=True, tol=0.001, verbose=False)

In [57]:
#predict test set result
y_pred=classifier.predict(X_test)

In [58]:
#making confusion Matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.7126436781609196

In [59]:
#Applying grid search cv
from sklearn.model_selection import GridSearchCV
parameters=[{'C':[1,10,100,1000],'kernel':['linear']},
           {'C':[1,10,100,1000],'kernel':['rbf'],'gamma':[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]}]
grid_search = GridSearchCV(estimator= classifier,param_grid=parameters,
                          scoring='accuracy',cv=10,n_jobs=-1)
grid_search=grid_search.fit(X_train,y_train)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [60]:
accuracy=grid_search.best_score_
accuracy

0.7170542635658915

In [61]:
grid_search.best_params_

{'C': 100, 'gamma': 0.1, 'kernel': 'rbf'}

In [62]:
#Fitting Kernel SVM to the Training set
from sklearn.svm import SVC
classifier =SVC(kernel='linear',gamma=0.1)
classifier.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [63]:
#predict test set result
y_pred=classifier.predict(X_test)

In [64]:
#making confusion Matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [65]:
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.7126436781609196

In [66]:
#Random Search CV

In [67]:
from sklearn.ensemble import RandomForestClassifier
classifier1=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=50)
classifier1.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=50, verbose=0,
                       warm_start=False)

In [68]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

In [69]:
est=RandomForestClassifier(n_jobs=-1)
rf_p_dist={'max_depth':[3,5,10,None],
          'n_estimators':[100,200,300,400,500],
          'max_features':randint(1,3),
          'criterion':['gini','entropy'],
          'bootstrap':[True,False],
          'min_samples_leaf':randint(1,4)}

In [70]:
def hypertuning_rscv(est,p_distr,nbr_iter,X,y):
    rdmsearch=RandomizedSearchCV(est,param_distributions=p_distr,
                                n_jobs=-1,n_iter=nbr_iter,cv=9)
    rdmsearch.fit(X,y)
    ht_params=rdmsearch.best_params_
    ht_score=rdmsearch.best_score_
    return ht_params,ht_score
rf_parameters,rf_ht_score=hypertuning_rscv(est,rf_p_dist,40,X,y)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [85]:
y_pred=classifier1.predict(X_test)
y_pred

array([2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1,
       2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1,
       2, 1, 1, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2],
      dtype=int64)

In [72]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)

In [73]:
accuracy_score=accuracy_score(y_test,y_pred)

In [74]:
rf_parameters

{'bootstrap': True,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 2,
 'min_samples_leaf': 3,
 'n_estimators': 100}

In [75]:
rf_ht_score

0.7478260869565218

In [77]:
accuracy_score

0.7126436781609196

In [97]:
classifier2=RandomForestClassifier(n_jobs=-1,n_estimators=100,bootstrap=True,criterion='entropy',max_depth=None,max_features= 2,min_samples_leaf=3)


In [90]:
df.dtypes

 mean corpuscular volume                                                         int64
alkphos alkaline phosphotase                                                     int64
sgpt alanine aminotransferase                                                    int64
 sgot aspartate aminotransferase                                                 int64
gammagt gamma-glutamyl transpeptidase                                            int64
drinks number of half-pint equivalents of alcoholic beverages drunk per day    float64
selector field created by the BUPA researchers                                   int64
dtype: object

In [98]:
classifier2.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=2, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [99]:
y_pred=classifier2.predict(X_test)
y_pred

array([2, 2, 2, 1, 1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1,
       2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1,
       2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2],
      dtype=int64)

In [100]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[17, 16],
       [ 6, 48]], dtype=int64)

In [101]:
accuracy_score=accuracy_score(y_test,y_pred)
accuracy_score
#increase in acuracy observed

0.7471264367816092

In [104]:
from sklearn.model_selection import cross_val_score
cross_val=cross_val_score(classifier2,X,y,cv=10,scoring='accuracy').mean()


In [105]:
cross_val

0.7247058823529413

In [107]:
#3. Logistic Regression
from sklearn.linear_model import LogisticRegression
classifier3 = LogisticRegression().fit(X_train,y_train)
y_pred = classifier3.predict(X_test)
y_pred

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2,
       2, 2, 1, 1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 1, 2, 2,
       2, 1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 2, 2],
      dtype=int64)

In [108]:
# Model Evaluation metrics 
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score
print('Accuracy Score : ' + str(accuracy_score(y_test,y_pred)))
print('Precision Score : ' + str(precision_score(y_test,y_pred)))
print('Recall Score : ' + str(recall_score(y_test,y_pred)))
print('F1 Score : ' + str(f1_score(y_test,y_pred)))

#Logistic Regression Classifier Confusion matrix
from sklearn.metrics import confusion_matrix
print('Confusion Matrix : \n' + str(confusion_matrix(y_test,y_pred)))

Accuracy Score : 0.7126436781609196
Precision Score : 0.6428571428571429
Recall Score : 0.5454545454545454
F1 Score : 0.5901639344262296
Confusion Matrix : 
[[18 15]
 [10 44]]


In [109]:
#Grid Search
from sklearn.model_selection import GridSearchCV
clf = LogisticRegression()
clf

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [110]:
grid_values = {'penalty': ['l1', 'l2'],'C':[0.001,.009,0.01,.09,1,5,10,25]}
grid_clf_acc = GridSearchCV(clf, param_grid = grid_values,scoring = 'recall')
grid_clf_acc.fit(X_train, y_train)
#predict y value
y_pred_acc=grid_clf_acc.predict(X_test)
y_pred_acc

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [111]:
# New Model Evaluation metrics 
print('Accuracy Score : ' + str(accuracy_score(y_test,y_pred_acc)))
print('Precision Score : ' + str(precision_score(y_test,y_pred_acc)))
print('Recall Score : ' + str(recall_score(y_test,y_pred_acc)))
print('F1 Score : ' + str(f1_score(y_test,y_pred_acc)))

#Logistic Regression (Grid Search) Confusion matrix
confusion_matrix(y_test,y_pred_acc)

Accuracy Score : 0.3793103448275862
Precision Score : 0.3793103448275862
Recall Score : 1.0
F1 Score : 0.5499999999999999


array([[33,  0],
       [54,  0]], dtype=int64)

In [115]:
# Grid Search for Algorithm Tuning
import numpy as np
from sklearn import datasets
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV


In [118]:
# load the linerude datasets
dataset = datasets.load_linnerud()
dataset

{'data': array([[  5., 162.,  60.],
        [  2., 110.,  60.],
        [ 12., 101., 101.],
        [ 12., 105.,  37.],
        [ 13., 155.,  58.],
        [  4., 101.,  42.],
        [  8., 101.,  38.],
        [  6., 125.,  40.],
        [ 15., 200.,  40.],
        [ 17., 251., 250.],
        [ 17., 120.,  38.],
        [ 13., 210., 115.],
        [ 14., 215., 105.],
        [  1.,  50.,  50.],
        [  6.,  70.,  31.],
        [ 12., 210., 120.],
        [  4.,  60.,  25.],
        [ 11., 230.,  80.],
        [ 15., 225.,  73.],
        [  2., 110.,  43.]]),
 'feature_names': ['Chins', 'Situps', 'Jumps'],
 'target': array([[191.,  36.,  50.],
        [189.,  37.,  52.],
        [193.,  38.,  58.],
        [162.,  35.,  62.],
        [189.,  35.,  46.],
        [182.,  36.,  56.],
        [211.,  38.,  56.],
        [167.,  34.,  60.],
        [176.,  31.,  74.],
        [154.,  33.,  56.],
        [169.,  34.,  50.],
        [166.,  33.,  52.],
        [154.,  34.,  64.],
        

In [119]:
# prepare a range of alpha values to test
alphas = np.array([1,0.1,0.01,0.001,0.0001,0])

In [120]:
# create and fit a ridge regression model, testing each alpha
model = Ridge()
grid = GridSearchCV(estimator=model, param_grid=dict(alpha=alphas))
grid.fit(dataset.data, dataset.target)
print(grid)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True,
                             max_iter=None, normalize=False, random_state=None,
                             solver='auto', tol=0.001),
             iid='warn', n_jobs=None,
             param_grid={'alpha': array([1.e+00, 1.e-01, 1.e-02, 1.e-03, 1.e-04, 0.e+00])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)


C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\base.py:420: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\base.py:420: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').


In [121]:
# summarize the results of the grid search
print(grid.best_score_)
print(grid.best_estimator_.alpha)

-0.8129106407845846
1.0


In [123]:
from sklearn.model_selection import RandomizedSearchCV

In [124]:
# load the diabetes datasets
dataset = datasets.load_linnerud()

In [126]:
# prepare a uniform distribution to sample for the alpha parameter
from scipy.stats import uniform as sp_rand
param_grid = {'alpha': sp_rand()}

In [127]:
# create and fit a ridge regression model, testing random alpha values
model = Ridge()
rsearch = RandomizedSearchCV(estimator=model, param_distributions=param_grid, n_iter=100)
rsearch.fit(dataset.data, dataset.target)
print(rsearch)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\base.py:420: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\base.py:420: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').


RandomizedSearchCV(cv='warn', error_score='raise-deprecating',
                   estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True,
                                   max_iter=None, normalize=False,
                                   random_state=None, solver='auto',
                                   tol=0.001),
                   iid='warn', n_iter=100, n_jobs=None,
                   param_distributions={'alpha': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000001D0851A4048>},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=False, scoring=None, verbose=0)


C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [128]:
# summarize the results of the random parameter search
print(rsearch.best_score_)
print(rsearch.best_estimator_.alpha)

-0.8129162982514397
0.9936727638511813


In [1]:
#tried  severl grid search and randamized search cv to the best of my knowledge